charts/prysm/ci/validator-values.yaml, charts/prysm/templates/_cmd.tpl
so that we can use shell commands on extraArgs if needed.
=> prysm: use shell as for validator cmd

charts/beaconchain-explorer/README.md, charts/beaconchain-explorer/values.yaml
`postgresqlDatabase: explorer` is needed for the serviceMonitor to work.
=> beaconchain-explorer: allocate disk space and define psql db by default

charts/geth/Chart.yaml, charts/geth/README.md, charts/geth/README.md.gotmpl, charts/geth/templates/_helpers.tpl, charts/geth/templates/service.p2p.nodeport.yaml, charts/geth/templates/statefulset.yaml, charts/geth/values.yaml
NodePort with the intermediary socat proxy wasn't working well with the P2P layer. 
This has the limitation that you can only run 1 Replica when using NodePort, but that can be worked around by deploying the chart multiple times.
=> geth: make nodePort work, with its limitations to a single replica

charts/nethermind/Chart.yaml, charts/nethermind/README.md, charts/nethermind/README.md.gotmpl, charts/nethermind/templates/_helpers.tpl, charts/nethermind/templates/service.p2p.nodeport.yaml, charts/nethermind/templates/statefulset.yaml, charts/nethermind/values.yaml
NodePort with the intermediary socat proxy wasn't working well with the P2P layer. This change has the limitation that you can only run 1 Replica when using NodePort, but that can be worked around by deploying the chart multiple times.
=> nethermind: make nodePort work, with its limitations to a single replica

charts/erigon/Chart.yaml, charts/erigon/README.md, charts/erigon/README.md.gotmpl, charts/erigon/templates/_helpers.tpl, charts/erigon/templates/service.p2p.nodeport.yaml, charts/erigon/templates/statefulset.yaml, charts/erigon/values.yaml
NodePort with the intermediary socat proxy wasn't working well with the P2P layer. This change has the limitation that you can only run 1 Replica when using NodePort, but that can be worked around by deploying the chart multiple times.
=> erigon: make nodePort work, with its limitations to a single replica

charts/besu/Chart.yaml, charts/besu/README.md, charts/besu/README.md.gotmpl, charts/besu/templates/_helpers.tpl, charts/besu/templates/service.p2p.nodeport.yaml, charts/besu/templates/statefulset.yaml, charts/besu/values.yaml
NodePort with the intermediary socat proxy wasn't working well with the P2P layer. This change has the limitation that you can only run 1 Replica when using NodePort, but that can be worked around by deploying the chart multiple times.
=> besu: make nodePort work, with its limitations to a single replica

charts/nimbus/Chart.yaml, charts/nimbus/README.md, charts/nimbus/README.md.gotmpl, charts/nimbus/templates/_helpers.tpl, charts/nimbus/templates/service.p2p.nodeport.yaml, charts/nimbus/templates/statefulset.yaml, charts/nimbus/values.yaml
NodePort with the intermediary socat proxy wasn't working well with the P2P layer. This change has the limitation that you can only run 1 Replica when using NodePort, but that can be worked around by deploying the chart multiple times.
=> nimbus: make nodePort work, with its limitations to a single replica

charts/nimbus/Chart.yaml, charts/nimbus/README.md, charts/nimbus/templates/service-headless.yaml, charts/nimbus/templates/service.yaml, charts/nimbus/templates/statefulset.yaml, charts/nimbus/values.yaml
Renames the Nimbus pod/service port `http-rpc` to `http-api` to align with the other conensus charts
=> fix(nimbus): Change port http-rpc to http-api

charts/dshackle/Chart.yaml, charts/dshackle/README.md
Chart Releaser wants to upload a new dshackle version: https://github.com/skylenet/ethereum-helm-charts/runs/8064796693?check_suite_focus=true
=> feat(dshackle): Bump version

charts/dshackle/Chart.yaml, charts/dshackle/README.md, charts/dshackle/templates/statefulset.yaml, charts/dshackle/values.yaml
OpenShift is notoriously strict on permissions and to deploy this chart without warnings we need to be able to set container level security contexts as well.
```
would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "dshackle" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "dshackle" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "dshackle" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```
default `helm create` generates `podSecurityContext` for pods and `securityContext` for containers, but to not break backwards compatibility I used the other convention you see which is `containerSecurityContext`.
=> feat: allow to set a container security context for OpenShift deployments

charts/ethereum-address-metrics-exporter/Chart.yaml, charts/ethereum-address-metrics-exporter/README.md, charts/ethereum-address-metrics-exporter/values.yaml
original PR https://github.com/skylenet/ethereum-helm-charts/pull/119 was wrong, these changes should exist upstream
=> revert(ethereum-address-metrics-exporter): target image version

charts/smart-contract-verifier-http/Chart.yaml, charts/smart-contract-verifier-http/README.md, charts/smart-contract-verifier-http/templates/_helpers.tpl, charts/smart-contract-verifier-http/values.yaml
It seems like that the config file wasn't been read at all. Adding the `SMART_CONTRACT_VERIFIER__CONFIG` fixed that. Also changed the default http port to be 8050 instead of 8043. The config file also had to change slightly due to the http.server config.  
fixes https://github.com/ethpandaops/ethereum-helm-charts/issues/159
=> smart-contract-verifier-http: fix http port and read config file

charts/beacon-metrics-gazer/Chart.yaml, charts/beacon-metrics-gazer/README.md, charts/beacon-metrics-gazer/templates/deployment.yaml
hard to review just by looking at the code diff, but basically nindent was off by 2. Because it was:
```yaml
containers:
- ...
```
instead of :
```yaml
containers:
- ...
```
This came to my attention due to a custom deployment I was doing when setting extraVolumeMounts:
```
ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): `bash -c VALUES_FILES="" for i in ${ARGOCD_ENV_HELM_OPTIONAL_VALUES_FILES//,/ } do if [ -f "${i}" ]; then VALUES_FILES="${VALUES_FILES} -f ${i}" fi done helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${VALUES_FILES[@]} ${ARGOCD_ENV_HELM_ARGS} --include-crds -f <(echo "$ARGOCD_ENV_HELM_VALUES") . | AVP_TYPE=sops SOPS_AGE_KEY_FILE=/keys/key argocd-vault-plugin generate - ` failed exit status 1: Error: YAML parse error on …
```
=> beacon-metrics-gazer: fixup indentation

charts/web3signer/Chart.yaml, charts/web3signer/README.md, charts/web3signer/values.yaml
- only download migrations if not currently in persistence
- when a migration is run create a corresponding completed empty file eg. `V00001__initial.sql.completed`
- don't run a migration if it already has a corresponding completed empty file
=> fix(web3signer): handle slashing protection migrations

charts/dora/Chart.yaml, charts/dora/README.md, charts/dora/values.yaml
The low `inMemoryEpochs` causes unneeded synchronizations in normal running networks, 
because blocks are evicted from memory before being finalized.
This is not breaking the explorer,  but causes some unwanted side effects that can currently be seen on the sepolia instance, which drops cached blocks before they're finalized-processed:
https://dora.sepolia.ethpandaops.io/epochs 
The synchronizer in the sepolia instance is still far behind, which makes the issue more visible
=> Increase `inMemoryEpochs` setting in dora config

charts/powfaucet/Chart.yaml, charts/powfaucet/README.md, charts/powfaucet/README.md.gotmpl, charts/powfaucet/values.yaml
powfaucet needs to know how many proxy servers are in front of it.
Otherwise it cannot safely select the correct remote IP from the list of forwarder addresses in the `X-Forwarded-For` header.
=> update powfaucet helm chart

charts/dugtrio/Chart.yaml, charts/dugtrio/README.md, charts/dugtrio/values.yaml
as discussed with sam on discord :)
=> Revert dugtrio pull policy and set version tag

charts/ethereum-node/Chart.lock, charts/ethereum-node/Chart.yaml, charts/ethereum-node/README.md, charts/reth/Chart.yaml, charts/reth/README.md, charts/reth/values.yaml
Closes #254 
- fix: use reth's flag `--log.file.directory` instead of the incorrect `--log.directory`
- fix: bump xatu-sentry to `0.0.8` in ethereum-node chart
=> fix(reth): log.file.directory flag

Makefile
Linting was failing due to: 
```
Error: failed linting charts: failed identifying charts to process: must be in a git repository
make: *** [lint] Error 1
````
So... git was complaining again suddenly about:
```
fatal: detected dubious ownership in repository at '/workdir'
```
Which indicates some problem with file permissions on the directory.
Checking the dir inside the container shows that indeed the bind mount is owned by "root":
```sh
7f95bad9358c:/workdir$ ls -la .
total 36
drwxr-xr-x   12 root     root           384 Dec 19 11:58 .
drwxr-xr-x    1 root     root          4096 Dec 19 12:04 ..
drwxr-xr-x   13 501      root           416 Dec 19 12:02 .git
drwxr-xr-x    4 501      root           128 Dec 19 11:58 .github
-rw-r--r--    1 501      root           147 Dec 19 11:58 .gitignore …
```
=> fix make lint 

.github/workflows/release.yaml
I've added directly `skip_existing: true` when trying to fix the recent release, it turns out it was just added in v.1.6.0 of that action. So I'm updating it.
=> chart releaser: bump version to support 'skip_existing'

charts/dora/Chart.yaml, charts/dora/README.md, charts/dora/values.yaml
Add `executionEndpoints` & `mevRelays`
=> Update dora helm chart

charts/ethereum-metrics-exporter/Chart.yaml, charts/ethereum-metrics-exporter/README.md, charts/ethereum-metrics-exporter/values.yaml
Default value for service monitor is wrong as scrape timeout is longer than scape interval, this is from prometheus operator with default value
error="scrapeTimeout \"30s\" greater than scrapeInterval \"15s\""
=> fix: change default service monitor values for ethereum-metrics-exporter

charts/ethereum-address-metrics-exporter/Chart.yaml, charts/ethereum-address-metrics-exporter/README.md, charts/ethereum-address-metrics-exporter/values.yaml
Default chart value for `ServiceMonitor` config is set with `interval` less than `scrapeTimeout`, which Grafana Alloy doesn't like:
```ts=2024-05-28T23:57:50.491815865Z level=error msg="error generating scrapeconfig from serviceMonitor" component_path=/ component_id=prometheus.operator.servicemonitors.service_monitors name=mainnet-mon-exporter err="scrape timeout greater than scrape interval for scrape config with job name \"serviceMonitor/default/mainnet-mon-exporter/0\""```
=> ethereum-address-metrics-exporter: raise ServiceMonitor interval

charts/erpc/.helmignore, charts/erpc/Chart.lock, charts/erpc/Chart.yaml, charts/erpc/README.md, charts/erpc/README.md.gotmpl, charts/erpc/templates/_helpers.tpl, charts/erpc/templates/configmap.yaml, charts/erpc/templates/deployment.yaml, charts/erpc/templates/ingress.yaml, charts/erpc/templates/secret.yaml, charts/erpc/templates/service.yaml, charts/erpc/templates/serviceaccount.yaml, charts/erpc/templates/servicemonitor.yaml, charts/erpc/templates/tests/test-connection.yaml, charts/erpc/values.yaml
Adds the [erpc](https://github.com/erpc/erpc) chart and closes #337 
I based my implementation and the relative config defaults on the [railway-deployment](https://github.com/erpc/railway-deployment) for erpc. I'm not a fan of having the config (which contains remote RPC apikeys) be stored in a configmap, but from how they use gotemplate to load env variables into the config file i assume erpc doesnt support config overrides from environment variables.
The [prepackaged docker image by erpc](https://github.com/erpc/erpc/blob/main/Dockerfile) is hardcoded to run as root. It's fairly easy to change that with a new Dockerfile but we would have to rehost the image on another registry and keep it updated. Not sure on what the policies are for that stuff, but i'm open to discuss
I didnt include …
=> feat: add erpc chart

.github/workflows/check-typos.yaml, .github/workflows/release.yaml, .github/workflows/test-charts.yaml, .github/workflows/test-ethereum-node.yaml
This PR updates GitHub Actions to use pinned commit hashes for better security.
=> Update GitHub Actions to use pinned hashes

.github/workflows/check-typos.yaml, .github/workflows/release.yaml, .github/workflows/test-charts.yaml, .github/workflows/test-ethereum-node.yaml
This PR updates GitHub Actions to use pinned commit hashes for better security.
=> Update github actions dependencies to show full versions in comment

charts/besu/Chart.yaml, charts/besu/README.md, charts/besu/templates/statefulset.yaml, charts/erigon/Chart.yaml, charts/erigon/README.md, charts/erigon/templates/statefulset.yaml, charts/ethereumjs/Chart.yaml, charts/ethereumjs/README.md, charts/ethereumjs/templates/statefulset.yaml, charts/geth/Chart.yaml, charts/geth/README.md, charts/geth/templates/statefulset.yaml, charts/grandine/Chart.yaml, charts/grandine/README.md, charts/grandine/templates/statefulset.yaml, charts/lighthouse/Chart.yaml, charts/lighthouse/README.md, charts/lighthouse/templates/statefulset.yaml, charts/reth/Chart.yaml, charts/reth/README.md, charts/reth/templates/statefulset.yaml
- Fixed init container ordering issue where `init-chown-data` was running before devnet init containers
- The devnet init containers create files as root, so `init-chown-data` must run after them to fix permissions
- This resolves permission denied errors when running with devnet enabled
Fixed init container ordering in the following charts by moving `init-chown-data` to run AFTER devnet init containers:
- ✅ geth (1.1.0 -> 1.1.1)
- ✅ besu (1.1.0 -> 1.1.1)  
- ✅ erigon (1.1.0 -> 1.1.1)
- ✅ ethereumjs (0.1.0 -> 0.1.1)
- ✅ reth (0.1.0 -> 0.1.1)
- ✅ grandine (0.2.0 -> 0.2.1)
- ✅ lighthouse (1.1.6 -> 1.1.7)
Note: nethermind, lodestar, prysm, and teku already had the correct ordering.
=> fix: correct init container ordering for devnet support
